# Day 2 Data wrangling with Python - Exercises

## Exercise 1

#### Question 1
##### Create an array of 25 numbers between 1 and 100 (including 100) and save to `arr1` variable.
##### Pring the type and data type of `arr1`.

#### Answer:

In [1]:
import numpy as np

In [2]:
arr1 = np.linspace(1,100,25)

In [3]:
arr1.dtype

dtype('float64')

In [5]:
arr1

array([  1.   ,   5.125,   9.25 ,  13.375,  17.5  ,  21.625,  25.75 ,
        29.875,  34.   ,  38.125,  42.25 ,  46.375,  50.5  ,  54.625,
        58.75 ,  62.875,  67.   ,  71.125,  75.25 ,  79.375,  83.5  ,
        87.625,  91.75 ,  95.875, 100.   ])

#### Question 2
##### Create an array of 20 numbers from 50 to 70 (excluding 70).
##### Use `arange` function and assign the output to `arr2` variable.

#### Answer:

In [8]:
arr2 = np.arange(50,70)
arr2

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69])

#### Question 3
##### Create an array of all even numbers between 30 and 60 (excluding 60).
##### Create an array of numbers between 0 and 100 (including 100), with step size of 25.

#### Answer:

In [9]:
np.arange(30,60,2)

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

In [10]:
np.arange(0,101,25)

array([  0,  25,  50,  75, 100])

#### Question 4
##### Create an array of 10 numbers between 0 and 20 (including 20) assign to `arr3` variable.
##### Use linspace function.
##### Find the max, min and sum of the array.

#### Answer:

In [14]:
arr3 = np.linspace(0,20,10)

In [15]:
np.max(arr3)

20.0

In [16]:
np.sum(arr3)

100.0

#### Question 5
##### Create two arrays of size 4 with the numbers 4, 5, 6, 4 in `array1` and 7, 2, 12, 16 in `array2`.
##### Find the `sum`,  `product`, `difference` and `quotient` of `array1` and `array2` and save as `array_sum`, `product`, `difference`, and `quotient` variables respectively.
##### Print the results.

#### Answer:

In [17]:
array1 = np.array([4,5,6,4])
array2 = np.array([7,2,12,16])

In [18]:
array_sum = array1 + array2
product = array1 * array2
difference = array1 - array2
quotient = array1 / array2

In [19]:
array_sum


array([11,  7, 18, 20])

In [20]:
product


array([28, 10, 72, 64])

In [21]:
difference 


array([ -3,   3,  -6, -12])

In [22]:
quotient

array([0.57142857, 2.5       , 0.5       , 0.25      ])

## Exercise 2

#### Question 1
##### Compute the absolute value of each entry in the following array `[5, -8, -66, 4]` and assign it to `abs_values` variable. Print the result.
##### Print the length of the `abs_values` array.
##### Print the 3rd element of `abs_values`.

#### Answer:

#### Question 2
##### Print all numbers greater than 25 in `abs_values` array.

#### Answer:

#### Question 3
##### Create a matrix with 3 rows and assign to variable `mat1`.
- [4, 5, 6]
- [8, 3, 2]
- [6, 7, 3]

##### Find the shape of the matrix.

#### Answer:

#### Question 4
##### Find the value in the 2nd row and 3rd column.
##### Print the 2nd and 3rd rows.
##### Print the 1st column and rows up to the 2nd row.
##### Print all columns starting with column 2.

#### Answer:

#### Question 5
##### Filter and print the elements greater than 5 in `mat1`.
##### Use a Boolean mask to filter all elements <= 5 and set them to 0.
##### Print the resulting matrix.

#### Answer:

#### Question 6
##### Create a `numpy` array of 16 numbers between 10 and 25 (inclusive), and call it `arr4`. Use linspace function.
##### Reshape the array to a matrix of shape (4,4) and print it.
##### Reshape the array to a matrix with 8 rows and let Python infer the number of columns.

#### Answer:

#### Question 7
##### Import `pandas` as `pd` and `os` packages.
##### Set the working directory to data directory.
##### Print the working directory.

#### Answer: